name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-a-docker-image-to-aws-ecr:
    uses: ./.github/workflows/publishing-images-to-AWS-ECR.yml
  deployment-to-dev:
    needs: build-and-publish-a-docker-image-to-aws-ecr
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: terraform
    steps:
    - name: Check env vars
      run: |
        echo "LAMBDA_NAME: ${{ vars.LAMBDA_NAME }}"
    - name: Terraform init
      run: |
        terraform init -input=false
    - name: Terraform apply
      run: |
        terraform apply -input=false -auto-approve
