name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Check env vars
        run: |
          echo "LAMBDA_NAME: ${{ vars.LAMBDA_NAME }}"
      - name: Terraform init
        run: |
          terraform init -input=false
      - name: Terraform apply
        run: |
          terraform apply -input=false -auto-approve
