name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Check terraform version
        run: |
            terraform version
      - name: Check env vars
        run: |
            echo "LAMBDA_NAME: ${{ vars.LAMBDA_NAME }}"